### ISSUE TITLE
Cannot deploy locally (issue in deploy.scen)

### ISSUE THREAD

**Issue by bschreck** [compound-finance/compound-protocol#86]
Running `yarn deploy` locally produces the following error:
```
error: Error: Failed to find string value by index (got undefined): [["Contracts","Comptroller"]], index contains: {"PriceOracle":{"description":"Fixed Price Oracle","address":"0x5dcf6E29b6c7e2a64F79416C84F959A2F0455fc6"},"Contracts":{"ZRX":"0x16405D3abB9e1066B9a71eb5FD93DABF4D23a058","PriceOracle":"0x5dcf6E29b6c7e2a64F79416C84F959A2F0455fc6","YesNo":"0x96d28812b1C1242E3fB21c981560f509029E1f91","DAI":"0x1d6ea546e9439DECC122DF9cFA50c0563d1bE8Be","StdInterest":"0x831dc59601481092e41E4Cf11F5b3f907dB2e954","Unitroller":"0x9B26Fb4c3004F63de1D1FF6bfDaD3ADA2b0F708D","BAT":"0x6473726c37357Fca32c74D6a6aeec703A0648B4C","Asdasdfas":"0xb21985b8d83640460c9Bd032593923A75b099eaF","REP":"0xB15801A4192eA9cD12820b4556593319E9B7B129","USDC":"0x4b778C79058976a74D5003D3953f133834Ea5832","ScenarioG5":"0xbaC2bD377f4cCb95C7D3515baEa2f6a3631D21A4","InterestRateModel":"0xcD28806E02fB05801361f724D35Ce59f223D0cE8"},"Constructors":{"ZRX":"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000001200000000000000000000000000000000000000000000000000000000000000c00000000000000000000000000000000000000000000000000000000000000002307800000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000035a52580000000000000000000000000000000000000000000000000000000000","PriceOracle":"0x0000000000000000000000000000000000000000000000000de0b6b3a7640000","YesNo":"0x","DAI":"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000001200000000000000000000000000000000000000000000000000000000000000c00000000000000000000000000000000000000000000000000000000000000003446169000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000034441490000000000000000000000000000000000000000000000000000000000","StdInterest":"0x0000000000000000000000000000000000000000000000000000048c27395000","Unitroller":"0x","BAT":"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000001200000000000000000000000000000000000000000000000000000000000000c00000000000000000000000000000000000000000000000000000000000000015426173696320417474656e74696f6e20546f6b656e000000000000000000000000000000000000000000000000000000000000000000000000000000000000034241540000000000000000000000000000000000000000000000000000000000","Asdasdfas":"0x","REP":"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000001200000000000000000000000000000000000000000000000000000000000000c00000000000000000000000000000000000000000000000000000000000000005417567757200000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000035245500000000000000000000000000000000000000000000000000000000000","USDC":"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000001200000000000000000000000000000000000000000000000000000000000000c00000000000000000000000000000000000000000000000000000000000000004555344430000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000045553444300000000000000000000000000000000000000000000000000000000","ScenarioG5":"0x","InterestRateModel":"0x00000000000000000000000000000000000000000000000000016bcc41e90000"},"Blocks":{"ZRX":4,"PriceOracle":4,"YesNo":1,"DAI":6,"StdInterest":2,"Unitroller":3,"BAT":5,"Asdasdfas":1,"REP":7,"USDC":1,"ScenarioG5":1,"InterestRateModel":3},"Comptroller":{"YesNo":{"address":"0x96d28812b1C1242E3fB21c981560f509029E1f91","contract":"ComptrollerScenario","description":"Scenario Comptroller Impl"},"Asdasdfas":{"address":"0xb21985b8d83640460c9Bd032593923A75b099eaF","contract":"ComptrollerScenario","description":"Scenario Comptroller Impl"},"ScenarioG5":{"address":"0xbaC2bD377f4cCb95C7D3515baEa2f6a3631D21A4","contract":"ComptrollerScenario","description":"Scenario Comptroller Impl"}},"InterestRateModel":{"InterestRateModel":{"name":"InterestRateModel","contract":"InterestRateModelHarness","description":"Fixed rate 0.04% per block","address":"0xcD28806E02fB05801361f724D35Ce59f223D0cE8"},"StdInterest":{"name":"StdInterest","contract":"InterestRateModelHarness","description":"Fixed rate 0.0005% per block","address":"0x831dc59601481092e41E4Cf11F5b3f907dB2e954"}},"Tokens":{"ZRX":{"description":"Standard","name":"0x","symbol":"ZRX","decimals":18,"contract":"FaucetToken","address":"0x16405D3abB9e1066B9a71eb5FD93DABF4D23a058"},"BAT":{"description":"NonStandard","name":"Basic Attention Token","symbol":"BAT","decimals":18,"contract":"FaucetNonStandardToken","address":"0x6473726c37357Fca32c74D6a6aeec703A0648B4C"},"DAI":{"description":"Standard","name":"Dai","symbol":"DAI","decimals":18,"contract":"FaucetToken","address":"0x1d6ea546e9439DECC122DF9cFA50c0563d1bE8Be"},"REP":{"description":"Standard","name":"Augur","symbol":"REP","decimals":18,"contract":"FaucetToken","address":"0xB15801A4192eA9cD12820b4556593319E9B7B129"},"USDC":{"description":"Standard","name":"USDC","symbol":"USDC","decimals":18,"contract":"FaucetToken","address":"0x4b778C79058976a74D5003D3953f133834Ea5832"}},"Unitroller":{"description":"Unitroller","address":"0x9B26Fb4c3004F63de1D1FF6bfDaD3ADA2b0F708D"}}
      at getContractDataString (/Users/bschreck/compound-protocol/scenario/src/ContractLookup.ts:46:11)
      at getWorldContract (/Users/bschreck/compound-protocol/scenario/src/ContractLookup.ts:57:19)
      at Arg.getComptroller [as getter] (/Users/bschreck/compound-protocol/scenario/src/ContractLookup.ts:89:10)
      at /Users/bschreck/compound-protocol/scenario/src/Command.ts:120:25
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
      at Fetcher.getArgs (/Users/bschreck/compound-protocol/scenario/src/Command.ts:103:53)
      at Fetcher.fetch (/Users/bschreck/compound-protocol/scenario/src/Command.ts:225:16),
  event: [
    'Gate',
    [ 'CToken', 'cZRX', 'Address' ],
    [
      'CToken', 'Deploy',
      'CErc20', 'cZRX',
      [Array],  [Array],
      [Array],  [Array],
      [Array],  [Array]
    ]
  ]
}
```

This is related to the first CToken initialization line in deploy.scen

**Comment by Holt666** [comment]
i have same issue

**Comment by BananaLF** [comment]
i have same issue @bschreck

**Comment by ajb413** [comment]
Try using Eureka: https://www.npmjs.com/package/@compound-finance/eureka
